language: c
script: bash -ex .travis-opam.sh
sudo: false
cache:
  directories:
    - $HOME/.opam
  before_cache:
    - opam remove bap -y
    - rm -rf $HOME/.opam/log
addons:
  apt:
    sources:
    - avsm
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    - llvm-toolchain-precise-3.8
    packages:
    - camlp4
    - camlp4-extra
    - clang
    - curl
    - libcurl4-gnutls-dev
    - libgmp-dev
    - libssl-dev
    - libzip-dev
    - llvm
    - llvm-3.4-dev
    - llvm-3.8-dev
    - m4
    - ocaml
    - ocaml-base
    - ocaml-base-nox
    - ocaml-compiler-libs
    - ocaml-native-compilers
    - ocaml-nox
    - time
    - aspcud
    - dejagnu

env:
  - FORK_USER=talex5 FORK_BRANCH=containers OPAMYES=true PACKAGE=bap OCAML_VERSION=latest TESTS=false llvm_version=3.8
  - FORK_USER=talex5 FORK_BRANCH=containers OPAMYES=true PACKAGE=bap OCAML_VERSION=latest TESTS=false llvm_version=3.4
